spring.application.name=test-manulife

# Database Configuration (Membaca Env Var dengan Fallback Nilai Default)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://pg-test-manulife-rizkitresnaningtyas-d3e5.c.aivencloud.com:26705/defaultdb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_8YzueaYut_vAebL1ihF}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=TestManulife-HikariCP

# OAuth Client Credentials
oauth.client.id=${OAUTH_CLIENT_ID:test-manulife}
oauth.client.secret=${OAUTH_CLIENT_SECRET:TESTMANULIFE123}